countries = [
    {"date":"1 January\n","name":"Brunei\n","year":"1984\n"},
    {"date":"1 January\n","name":"Sudan\n","year":"1956\n"},
    {"date":"4 January\n","name":"Myanmar\n","year":"1948\n"},
    {"date":"31 January\n","name":"Nauru\n","year":"1968\n"},
    {"date":"4 February\n","name":"Sri Lanka\n","year":"1948\n"},
    {"date":"7 February\n","name":"Grenada\n","year":"1974\n"},
    {"date":"18 February\n","name":"The Gambia\n","year":"1965\n"},
    {"date":"22 February\n","name":"Saint Lucia\n","year":"1979\n"},
    {"date":"28 February\n","name":"Egypt\n","year":"1922\n"},
    {"date":"6 March\n","name":"Ghana\n","year":"1957\n"},
    {"date":"12 March\n","name":"Mauritius\n","year":"1968\n"},
    {"date":"18 April\n","name":"Zimbabwe\n","year":"1980\n"},
    {"date":"27 April\n","name":"Sierra Leone\n","year":"1961\n"},
    {"date":"14 May\n","name":"Israel\n","year":"1948\n"},
    {"date":"25 May\n","name":"Jordan\n","year":"1946\n"},
    {"date":"26 May\n","name":"Guyana\n","year":"1966\n"},
    {"date":"4 June\n","name":"Tonga\n","year":"1970\n"},
    {"date":"19 June\n","name":"Kuwait\n","year":"1961\n"},
    {"date":"26 June\n","name":"Somaliland\n","year":"1960\n"},
    {"date":"29 June\n","name":"Seychelles\n","year":"1976\n"},
    {"date":"4 July\n","name":"United States\n","year":"1776\n"},
    {"date":"6 July\n","name":"Malawi\n","year":"1964\n"},
    {"date":"7 July\n","name":"Solomon Islands\n","year":"1978\n"},
    {"date":"10 July\n","name":"The Bahamas\n","year":"1973\n"},
    {"date":"12 July\n","name":"Kiribati\n","year":"1979\n"},
    {"date":"26 July\n","name":"Maldives\n","year":"1965\n"},
    {"date":"30 July\n","name":"Vanuatu\n","year":"1980\n"},
    {"date":"6 August\n","name":"Jamaica\n","year":"1962\n"},
    {"date":"14 August\n","name":"Pakistan\n","year":"1947\n"},
    {"date":"15 August\n","name":"Bahrain\n","year":"1971\n"},
    {"date":"15 August\n","name":"India\n","year":"1947\n"},
    {"date":"16 August\n","name":"Cyprus\n","year":"1960\n"},
    {"date":"19 August\n","name":"Afghanistan\n","year":"1919\n"},
    {"date":"31 August\n","name":"Trinidad and Tobago\n","year":"1962\n"},
    {"date":"31 August\n","name":"Malaya\n","year":"1957\n"},
    {"date":"3 September\n","name":"Qatar\n","year":"1971\n"},
    {"date":"6 September\n","name":"Eswatini\n","year":"1968\n"},
    {"date":"19 September\n","name":"Saint Kitts and Nevis\n","year":"1983\n"},
    {"date":"21 September\n","name":"Belize\n","year":"1981\n"},
    {"date":"21 September\n","name":"Malta\n","year":"1964\n"},
    {"date":"30 September\n","name":"Botswana\n","year":"1966\n"},
    {"date":"1 October\n","name":"Tuvalu\n","year":"1978\n"},
    {"date":"1 October\n","name":"Nigeria\n","year":"1960\n"},
    {"date":"3 October\n","name":"Iraq\n","year":"1932\n"},
    {"date":"4 October\n","name":"Lesotho\n","year":"1966\n"},
    {"date":"9 October\n","name":"Uganda\n","year":"1962\n"},
    {"date":"10 October\n","name":"Fiji\n","year":"1970\n"},
    {"date":"24 October\n","name":"Zambia\n","year":"1964\n"},
    {"date":"27 October\n","name":"Saint Vincent and the Grenadines\n","year":"1979\n"},
    {"date":"1 November\n","name":"Antigua and Barbuda\n","year":"1981\n"},
    {"date":"3 November\n","name":"Dominica\n","year":"1978\n"},
    {"date":"30 November\n","name":"South Yemen\n","year":"1967\n"},
    {"date":"30 November\n","name":"Barbados\n","year":"1966\n"},
    {"date":"2 December\n","name":"United Arab Emirates\n","year":"1971\n"},
    {"date":"9 December\n","name":"Tanganyika\n","year":"1961\n"},
    {"date":"10 December\n","name":"Zanzibar\n","year":"1963\n"},
    {"date":"12 December\n","name":"Kenya\n","year":"1963\n"},
    {"date":"20 December\n","name":"Oman\n","year":"1970\n"},
    {"date":"24 December\n","name":"Libya\n","year":"1951\n"}
]

const today = new Date();

const monthNames = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
]; 
const day = today.getDate(); // Returns the day of the month (1-31)
const month = monthNames[today.getMonth()]; // Returns the month (0-11), so we add 1

document.getElementById("answer").innerHTML = "Today is day " + day + " of month " + month + ". Now go check Wikipedia.";
